console.log("Hello".toUpperCase())
console.log("Hello".toLowerCase())

console.log("|      |")
console.log("|      |")
console.log("|      |")
console.log("________")
console.log("|      |")
console.log("|      |")
console.log("|      |")
console.log("________")
console.log("|      |")
console.log("|      |")
console.log("|      |")
console.log("________")